version: '3.8'

services:
  # The Toodle app served by Bun
  toodle:
    image: ghcr.io/nicbet/toodle:latest
    environment:
      - PORT=3000
    # No exposed ports - only accessible via Caddy
    networks:
      - internal

  # Caddy for TLS termination and reverse proxy
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
    depends_on:
      - toodle

volumes:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge